# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "DemoGithubActions",
      clean: true
    )
  end

  desc "Build for iOS Simulator"
  lane :build_simulator do
    gym(
      scheme: "DemoGithubActions", # Thay bằng scheme của bạn
      clean: true,
      skip_codesigning: true,
      skip_archive: true,
      destination: "platform=iOS Simulator,name=iPhone 16,OS=18.2",
      configuration: "Debug",
      xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO"
    )
  end
end