name: iOS CI

# Kích hoạt workflow khi push hoặc pull request vào nhánh main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Sử dụng runner macOS mới nhất
    runs-on: macos-15

    steps:
      # Clone mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Chọn phiên bản Ruby phù hợp
          # bundler-cache: true # Cache gem để tăng tốc

      - name: Install dependencies
        run: bundle install

      # Cài đặt phiên bản Xcode cụ thể
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Run Fastlane tests
        run: bundle exec fastlane test
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer # Thay bằng phiên bản Xcode phù hợp

      - name: Build app
        run: bundle exec fastlane build
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer
